// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJe-664myGCO8AQik1BQylSQrip9tzNLw',
    appId: '1:814056118844:web:498c5de116585aee82c139',
    messagingSenderId: '814056118844',
    projectId: 'valentine-544b0',
    authDomain: 'valentine-544b0.firebaseapp.com',
    storageBucket: 'valentine-544b0.firebasestorage.app',
    measurementId: 'G-MEY85QLWPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmtNURqWtbr6yvXZHmBzA2uCc7Od207co',
    appId: '1:814056118844:android:8cbd85a050329a8b82c139',
    messagingSenderId: '814056118844',
    projectId: 'valentine-544b0',
    storageBucket: 'valentine-544b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIZK4br_Vfa8MA0R-9sYzLcT_Px6f3m0M',
    appId: '1:814056118844:ios:68ca86777ee13d0d82c139',
    messagingSenderId: '814056118844',
    projectId: 'valentine-544b0',
    storageBucket: 'valentine-544b0.firebasestorage.app',
    iosClientId: '814056118844-ilh6at2o9m6ksgaei6g0023b2ufgkv83.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibeu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIZK4br_Vfa8MA0R-9sYzLcT_Px6f3m0M',
    appId: '1:814056118844:ios:68ca86777ee13d0d82c139',
    messagingSenderId: '814056118844',
    projectId: 'valentine-544b0',
    storageBucket: 'valentine-544b0.firebasestorage.app',
    iosClientId: '814056118844-ilh6at2o9m6ksgaei6g0023b2ufgkv83.apps.googleusercontent.com',
    iosBundleId: 'com.example.vibeu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJe-664myGCO8AQik1BQylSQrip9tzNLw',
    appId: '1:814056118844:web:f87087199bd5e4f582c139',
    messagingSenderId: '814056118844',
    projectId: 'valentine-544b0',
    authDomain: 'valentine-544b0.firebaseapp.com',
    storageBucket: 'valentine-544b0.firebasestorage.app',
    measurementId: 'G-F2XN3P374S',
  );
}
